<?php
namespace CakeAuth\Controller\Admin;

use Cake\Event\Event;
use CakeAuth\Controller\AbstractUsersController;
use CakeAuth\Controller\AppController;

/**
 * Users Controller
 *
 * @property \CakeAuth\Model\Table\UsersTable $Users
 */
class UsersController extends AbstractUsersController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->deny();
    }
}
