<?php
namespace CakeAuth\Controller\Admin;

use Cake\Event\Event;
use CakeAuth\Controller\AbstractUsersController;
use CakeAuth\Controller\AppController;

/**
 * Users Controller
 *
 * @property \CakeAuth\Model\Table\UsersTable $Users
 */
class UsersController extends AbstractUsersController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->deny();

        $this->loadComponent('CakeFile.Uploader', [
            'upload_domain' => 'users',
            'upload_dir' => 'images',
            'allowed' => ['png', 'jpg', 'jpeg', 'gif']
        ]);
    }

    public function updateImage($id = null)
    {
        $user = $this->Users->get($id);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->data);
            $user->image = $this->Uploader->upload($user->image_file);
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The node has been saved.'));
                return $this->redirect(['action' => 'view', $id]);
            }
        }
    }
}
